### ISSUE TITLE
Error When Running UserEnum_RPC.py

### ISSUE THREAD

**Issue by nullsession0x** [sensepost/UserEnum#4]
Hello,

When running UserEnum_RPC.py with the following variables I get the following error.
./UserEnum_RPC.py 192.168.1.97 userslist.txt 

Error:
[*] Connecting to 192.168.1.97
Traceback (most recent call last):
  File "./UserEnum_RPC.py", line 44, in <module>
    dce.connect()
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 801, in connect
    return self._transport.connect()
  File "/usr/local/lib/python2.7/dist-packages/impacket/dcerpc/v5/transport.py", line 393, in connect
    self.__tid = self.__smb_connection.connectTree('IPC$')
  File "/usr/local/lib/python2.7/dist-packages/impacket/smbconnection.py", line 378, in connectTree
    return self._SMBConnection.connect_tree(share)
  File "/usr/local/lib/python2.7/dist-packages/impacket/smb3.py", line 863, in connectTree
    packetID = self.sendSMB(packet)
  File "/usr/local/lib/python2.7/dist-packages/impacket/smb3.py", line 354, in sendSMB
    self.signSMB(packet)
  File "/usr/local/lib/python2.7/dist-packages/impacket/smb3.py", line 320, in signSMB
    signature = crypto.AES_CMAC(self._Session['SigningKey'], p, len(p))
  File "/usr/local/lib/python2.7/dist-packages/impacket/crypto.py", line 143, in AES_CMAC
    AES_128= AES.new(K)
TypeError: new() takes at least 2 arguments (1 given)

Any ideas what this might be?

**Comment by randomwalksp** [comment]
Hi,

seems to be an issue with impacket when you install pycryptodome, as discussed here:
https://github.com/CoreSecurity/impacket/issues/349

Try to run `pip uninstall pycryptodome`, or use virtualenv with only the required python packages.

Let me know if that works.

Regards
Reino Mostert
